<template>
  <aside class="sidebar-shell relative flex h-full min-h-0 w-full flex-col overflow-hidden text-white">
    <div class="sidebar-brand window-no-drag shrink-0"><img :src="logoUrl" alt="ContraBooks" class="brand-logo" draggable="false" /></div>
    <nav class="window-no-drag min-h-0 flex-1 overflow-y-auto px-3 pb-4 no-scrollbar" aria-label="Main navigation">
      <button v-for="item in navigation" :key="item.label" class="sidebar-item" :class="isActive(item.route) ? 'sidebar-active' : 'sidebar-inactive'" type="button" @click="routeTo(item.route)"><feather-icon :name="item.icon" class="nav-icon" /><span class="truncate">{{ item.label }}</span></button>
      <div class="sidebar-divider"></div>
      <div class="quick-heading"><span>{{ t`Quick Links` }}</span><span class="quick-plus">+</span></div>
      <button v-for="item in quickLinks" :key="item.label" class="sidebar-item quick-item" :class="isActive(item.route) ? 'sidebar-active' : 'sidebar-inactive'" type="button" @click="routeTo(item.route)"><feather-icon :name="item.icon" class="nav-icon" /><span class="truncate">{{ item.label }}</span></button>
      <button class="sidebar-item quick-item" :class="$route.path === '/backup-wizard' ? 'sidebar-active' : 'sidebar-inactive'" type="button" @click="routeTo('/backup-wizard')"><feather-icon name="shield" class="nav-icon" /><span class="truncate">{{ t`Backup & Export` }}</span></button>
    </nav>
    <div class="sidebar-footer window-no-drag shrink-0"><div class="footer-product">ContraBooks Desktop Pro</div><div class="footer-version">v2026.9.1</div></div>
    <button class="collapse-button" aria-label="Collapse sidebar" type="button" @click="() => toggleSidebar()"><feather-icon name="chevrons-left" /></button>
  </aside>
</template>
<script lang="ts">
import { t } from 'fyo';
import logoUrl from 'src/assets/img/contrabooks-logo.svg';
import { shortcutsKey } from 'src/utils/injectionKeys';
import { routeTo, toggleSidebar } from 'src/utils/ui';
import { defineComponent, inject } from 'vue';
const COMPONENT_NAME='Sidebar'; type SidebarLink={label:string;icon:string;route:string};
export default defineComponent({name:'Sidebar',props:{darkMode:{type:Boolean,default:false}},emits:['change-db-file','toggle-darkmode'],setup(){return{shortcuts:inject(shortcutsKey)};},data(){return{logoUrl,navigation:[{label:t`Dashboard`,icon:'home',route:'/'},{label:t`Banking`,icon:'home',route:'/list/Account'},{label:t`Sales`,icon:'shopping-cart',route:'/list/SalesInvoice'},{label:t`Customers`,icon:'users',route:'/list/Party/Customers'},{label:t`Vendors`,icon:'truck',route:'/list/Party/Suppliers'},{label:t`Employees`,icon:'user',route:'/list/Party/Employees'},{label:t`Transactions`,icon:'dollar-sign',route:'/list/Payment'},{label:t`Reports`,icon:'bar-chart-2',route:'/report/ProfitAndLoss'},{label:t`Accounting`,icon:'book-open',route:'/list/JournalEntry'},{label:t`Projects`,icon:'briefcase',route:'/settings'},{label:t`Inventory`,icon:'package',route:'/list/StockMovement'},{label:t`Taxes`,icon:'percent',route:'/list/Tax'}] as SidebarLink[],quickLinks:[{label:t`Create Invoice`,icon:'file-plus',route:'/list/SalesInvoice'},{label:t`Receive Payment`,icon:'credit-card',route:'/list/Payment'},{label:t`Make Deposit`,icon:'download',route:'/list/Payment'},{label:t`Write Check`,icon:'edit-3',route:'/list/Payment'},{label:t`Reconcile`,icon:'refresh-cw',route:'/list/BankReconciliation'},{label:t`Journal Entry`,icon:'book-open',route:'/list/JournalEntry'},{label:t`Bank Feed`,icon:'download',route:'/list/BankStatementEntry'},{label:t`Run Report`,icon:'bar-chart-2',route:'/report/GeneralLedger'}] as SidebarLink[]};},mounted(){this.shortcuts?.shift.set(COMPONENT_NAME,['KeyH'],()=>{if(document.body===document.activeElement)this.toggleSidebar();});this.shortcuts?.set(COMPONENT_NAME,['F1'],()=>this.openDocumentation());},unmounted(){this.shortcuts?.delete(COMPONENT_NAME);},methods:{routeTo,toggleSidebar,isActive(route:string){const current=this.$route.path;if(route==='/')return current==='/';return current===route||current.startsWith(`${route}/`);},openDocumentation(){ipc.openLink('https://github.com/dicarlop/ContraBooks');}}});
</script>
<style scoped>
.sidebar-shell{background:linear-gradient(180deg,#07345C 0%,#062B4A 100%)}.sidebar-brand{box-sizing:border-box;width:206px;margin:0 auto;padding:14px 0 11px;overflow:hidden;display:flex;justify-content:center}.brand-logo{display:block;width:206px;max-width:206px;height:auto;margin:0;opacity:.98}.sidebar-item{display:flex;align-items:center;width:100%;height:40px;gap:12px;margin:2px 0;padding:0 12px;border:0;border-radius:9px;text-align:left;font-size:14px;font-weight:500;transition:background-color 140ms ease,color 140ms ease,box-shadow 140ms ease}.nav-icon{width:18px!important;height:18px!important;min-width:18px;max-width:18px;flex:0 0 18px;stroke-width:2}.sidebar-active{background:linear-gradient(90deg,#00AFC1 0%,#007FA9 100%);color:#fff;box-shadow:0 5px 14px rgba(0,0,0,.18)}.sidebar-inactive{color:#E1EEF7}.sidebar-inactive:hover{background:rgba(24,198,211,.12);color:#fff}.sidebar-divider{height:1px;margin:14px 8px 12px;background:rgba(255,255,255,.12)}.quick-heading{display:flex;align-items:center;justify-content:space-between;height:28px;padding:0 12px;color:#A9C7DB;font-size:12px;font-weight:600}.quick-plus{font-size:19px;font-weight:400;line-height:1}.quick-item{height:38px;font-size:13px}.sidebar-footer{padding:14px 18px 18px;border-top:1px solid rgba(255,255,255,.1)}.footer-product{color:#8EAFC7;font-size:10px;font-weight:600}.footer-version{margin-top:2px;color:#6F91AB;font-size:10px}.collapse-button{position:absolute;right:7px;bottom:8px;display:grid;place-items:center;width:24px;height:24px;border:0;border-radius:6px;color:#8EAFC7;background:transparent;opacity:.5}.collapse-button:hover{background:rgba(255,255,255,.08);color:#fff;opacity:1}.collapse-button svg{width:15px!important;height:15px!important}
</style>